# Generated by Django 5.2 on 2025-04-16 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetAdoptionFeesMixin',
            fields=[
                ('category', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('adoption_fees', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BirdAdoptionFees',
            fields=[
                ('petadoptionfeesmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adoption_fees.petadoptionfeesmixin')),
            ],
            bases=('adoption_fees.petadoptionfeesmixin', models.Model),
        ),
        migrations.CreateModel(
            name='CatAdoptionFees',
            fields=[
                ('petadoptionfeesmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adoption_fees.petadoptionfeesmixin')),
            ],
            bases=('adoption_fees.petadoptionfeesmixin', models.Model),
        ),
        migrations.CreateModel(
            name='DogAdoptionFees',
            fields=[
                ('petadoptionfeesmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='adoption_fees.petadoptionfeesmixin')),
            ],
            bases=('adoption_fees.petadoptionfeesmixin', models.Model),
        ),
    ]
