# Generated by Django 5.2 on 2025-04-06 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('adoption_status', models.CharField(max_length=100)),
            ],
        ),
    ]
