# Generated by Django 5.2 on 2025-04-06 22:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_person_pet_adopted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=250)),
                ('unit_number', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('province', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(blank=True, null=True)),
                ('appointment_duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('reason', models.CharField(blank=True, choices=[('pet_visit', 'Meet and greet pet(s)'), ('general', 'Meet staff member/General queries'), ('pet_pickup', 'Picking up an approved pet'), ('other', 'Other')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IDProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_picture', models.FileField(help_text='.jpg, .jpeg, .png, .pdf files allowed', upload_to='id_uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_at_this_address', to='pets.address'),
        ),
        migrations.AddField(
            model_name='person',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_at_this_appointment', to='pets.appointment'),
        ),
        migrations.AddField(
            model_name='person',
            name='id_proof',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_of_person', to='pets.idproof'),
        ),
        migrations.CreateModel(
            name='PetPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_photos', to='pets.pet')),
            ],
        ),
    ]
