# Generated by Django 5.2 on 2025-04-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_address_appointment_idproof_alter_person_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idproof',
            name='id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idproof',
            name='id_type',
            field=models.CharField(blank=True, choices=[('drivers_license', 'Drivers License'), ('govt_id', 'Province Issue ID'), ('pr_card', 'Permanent Residence Card'), ('passport', 'Valid Passport'), ('other', 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='petphotos',
            name='alternate_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='petphotos',
            name='display_pic',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petphotos',
            name='images',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='pet_pics_upload', width_field='image_width'),
        ),
    ]
