# Generated by Django 5.2 on 2025-04-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_idproof_id_number_idproof_id_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphotos',
            name='images',
            field=models.ImageField(blank=True, height_field='200px', null=True, upload_to='pet_pics_upload', width_field='200px'),
        ),
    ]
