# Generated by Django 5.2 on 2025-04-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_petphotos_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphotos',
            name='images',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='pet_pics_upload', width_field='image_width'),
        ),
    ]
