# Generated by Django 5.2 on 2025-04-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_petphotos_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petphotos',
            old_name='images',
            new_name='image',
        ),
        migrations.AddField(
            model_name='petphotos',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='petphotos',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
