# Generated by Django 5.2 on 2025-04-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_rename_images_petphotos_image_petphotos_image_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('Dogs', 'Dog'), ('Cats', 'Cat'), ('Birds', 'Bird')]),
        ),
        migrations.AlterField(
            model_name='petphotos',
            name='image',
            field=models.ImageField(default='static/pets/photo_coming_soon.png', height_field='image_height', upload_to='pet_pics_upload', width_field='image_width'),
        ),
    ]
