# Generated by Django 5.2 on 2025-04-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_alter_pet_type_alter_petphotos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='interested_species',
            field=models.CharField(blank=True, choices=[('DOG', 'dog'), ('CAT', 'cat'), ('BIRD', 'bird')], null=True),
        ),
        migrations.AlterField(
            model_name='petphotos',
            name='image',
            field=models.ImageField(default='pet_pics_upload/photo_coming_soon.png', height_field='image_height', upload_to='pet_pics_upload', width_field='image_width'),
        ),
    ]
