# Generated by Django 5.2 on 2025-04-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_alter_person_interested_species_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='adopted_by',
        ),
        migrations.RemoveField(
            model_name='petphotos',
            name='display_pic',
        ),
        migrations.AddField(
            model_name='pet',
            name='display_pic',
            field=models.ImageField(default='pet_pics_upload/photo_coming_soon.png', height_field='image_height', upload_to='pet_display_pics_upload', width_field='image_width'),
        ),
    ]
