# Generated by Django 5.2 on 2025-04-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_remove_pet_adopted_by_remove_petphotos_display_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='display_pic',
            field=models.ImageField(default='pet_pics_upload/photo_coming_soon.png', height_field='image_height', max_length=200, upload_to='pet_display_pics_upload', width_field='image_width'),
        ),
    ]
