# Generated by Django 5.2 on 2025-04-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_remove_petphotos_image_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphotos',
            name='image',
            field=models.ImageField(blank=True, default='pet_pics_upload/photo_coming_soon.png', null=True, upload_to='pet_pics_upload'),
        ),
    ]
