# Generated by Django 5.2 on 2025-04-12 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0013_alter_petphotos_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='adopted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pets.person'),
        ),
    ]
