# Generated by Django 5.2 on 2025-04-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_pet_adopted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_time_owner',
            field=models.BooleanField(help_text='Please check this box if this will be your first pet'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(max_length=1200),
        ),
    ]
