# Generated by Django 5.2 on 2025-04-19 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0015_alter_person_first_time_owner_alter_person_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_at_this_appointment', to='pets.appointment'),
        ),
    ]
