# Generated by Django 5.2 on 2025-04-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_alter_person_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, choices=[('pet_visit', 'Meet and greet pet(s)'), ('general', 'Meet staff member/General queries'), ('pet_pickup', 'Picking up an approved pet'), ('other', 'Other')], default='other', null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='adoption_status',
            field=models.CharField(choices=[('adoptable', 'Adoptable'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('adopted', 'Adopted')]),
        ),
    ]
