# Generated by Django 5.2 on 2025-04-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0017_alter_appointment_reason_alter_pet_adoption_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(verbose_name={'female': 'female', 'male': 'male'}),
        ),
    ]
