# Generated by Django 5.2 on 2025-04-27 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0020_remove_person_address_remove_person_id_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='adopted_by',
        ),
    ]
