# Generated by Django 5.2 on 2025-04-27 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0022_pet_adopted_by'),
        ('user_profile', '0002_remove_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='user_profile.userprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
