# Generated by Django 5.2 on 2025-04-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Dogs', 'Dog'), ('Cats', 'Cat'), ('Birds', 'Bird')], max_length=50)),
                ('age_category', models.CharField(max_length=100)),
                ('fees', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
