# Generated by Django 5.2 on 2025-04-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_rename_age_category_petfee_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petfee',
            old_name='category',
            new_name='age_category',
        ),
    ]
