# Generated by Django 5.2 on 2025-04-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_rename_category_petfee_age_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petfee',
            name='type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('birds', 'Bird')], max_length=50),
        ),
    ]
