# Generated by Django 5.2 on 2025-04-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_alter_petfee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petfee',
            name='type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird')], max_length=50),
        ),
    ]
