# Generated by Django 5.2 on 2025-04-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_alter_petfee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petfee',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
