# Generated by Django 5.2 on 2025-04-26 22:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0019_alter_pet_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('interested_species', models.CharField(blank=True, choices=[('DOG', 'dog'), ('CAT', 'cat'), ('BIRD', 'bird')], null=True)),
                ('first_time_owner', models.BooleanField(help_text='Please check this box if this will be your first pet')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_at_this_address', to='pets.address')),
                ('id_proof', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_of_this_user', to='pets.idproof')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
